name: few-shot-segmentation
channels:
- default
dependencies:
- python=3.5
- pip
- pip:
  - matplotlib
  - numpy
  - torch
  - torchvision
  - nibabel
  - tensorboardX
  - 'tensorflow  '
  - torchnet
  - '# squeeze-and-excitation   --> Doesnt work at the moment. install manually from
    git repo'
  - '# nn-common-modules --> Doesnt work at the moment. install manually from git
    repo'
  - '# nn-additional-losses --> Doesnt work at the moment. install manually from git
    repo'
